/* Authenticated private workspace; versioned writes prevent silent overwrites. */
(()=>{
 const config=window.BBF_CONFIG||{};let client,user=null,ready=false,revision=0,lastSaved='',timer,inFlight=false,blocked=false,sessionEpoch=0;
 const gate=document.querySelector('#authGate'),message=document.querySelector('#authMessage');
 const tabId=sessionStorage.getItem('bbf-tab')||crypto.randomUUID();sessionStorage.setItem('bbf-tab',tabId);
 const pendingKey=()=>`bbf-pending:${user.id}:${tabId}`;
 function status(text,kind=''){const el=document.querySelector('#saveState');if(el){el.textContent=text;el.dataset.sync=kind}}
 function lock(text='Zaloguj się, aby otworzyć projekty.'){ready=false;document.documentElement.classList.add('auth-locked');gate.hidden=false;message.textContent=text}
 function resetHistory(){timeline={base:dataSnapshot(),entries:[],cursor:0};historyGroup++;updateHistoryButtons()}
 function payload(){return dataSnapshot()}
 function banner(text,buttons=[]){const el=document.querySelector('#syncBanner');el.replaceChildren(document.createTextNode(text));buttons.forEach(([label,fn])=>{const b=document.createElement('button');b.className='ghost';b.textContent=label;b.onclick=fn;el.append(b)});el.hidden=false}
 function cache(data){try{localStorage.setItem(pendingKey(),JSON.stringify({revision,data}))}catch(e){banner('Nie można zachować lokalnej kopii zmian. Pozostaw tę kartę otwartą do zakończenia zapisu.')}}
 function backup(){download(new Blob([JSON.stringify({...payload(),ui:state.ui},null,2)],{type:'application/json'}),'BBF-projects-backup.json')}
 function apply(data){const ui=state.ui;state={...clone(defaults),...clone(data||{}),ui};state.projectTypes??=clone(initialProjectTypes);state.targets??={margin:null,retention:null};state.projects.forEach(ensureStructure);if(!state.projects.some(p=>p.id===ui.selectedProject)){ui.selectedProject=state.projects[0]?.id;ui.tab=state.projects.length?'info':'dashboard'}resetHistory()}
 async function remote(){const {data,error}=await client.from('bbf_workspaces').select('data,revision').eq('owner_id',user.id).maybeSingle();if(error)throw error;return data}
 async function hydrate(nextUser){
  const epoch=++sessionEpoch;user=nextUser;ready=false;blocked=false;document.querySelector('#app').inert=false;lock('Wczytywanie projektów…');
  try{const row=await remote();if(epoch!==sessionEpoch)return;revision=row?.revision||0;apply(row?.data);lastSaved=JSON.stringify(payload());ready=true;gate.hidden=true;document.documentElement.classList.remove('auth-locked');render();status('Zapisano w chmurze');
   const raw=localStorage.getItem(pendingKey());if(raw){const saved=JSON.parse(raw);if(JSON.stringify(saved.data)!==lastSaved){blocked=true;document.querySelector('#app').inert=true;banner('Odnaleziono niezapisane zmiany z tego urządzenia.',[['Pobierz kopię',()=>download(new Blob([JSON.stringify(saved.data,null,2)],{type:'application/json'}),'BBF-odzyskane.json')],['Zastąp chmurę moją kopią',()=>{apply(saved.data);blocked=false;document.querySelector('#app').inert=false;document.querySelector('#syncBanner').hidden=true;render();queueSave()}],['Użyj chmury',()=>{localStorage.removeItem(pendingKey());blocked=false;document.querySelector('#app').inert=false;document.querySelector('#syncBanner').hidden=true}]])}else localStorage.removeItem(pendingKey())}
  }catch(e){lock('Nie udało się wczytać danych. Sprawdź połączenie lub konfigurację bazy.');document.querySelector('#cloudRetry').hidden=false}
 }
 function queueSave(){if(!ready||!user||blocked)return;const data=payload();if(JSON.stringify(data)===lastSaved)return;cache(data);status('Zapisywanie…','saving');clearTimeout(timer);timer=setTimeout(flush,500)}
 async function flush(){
  if(!ready||!user||blocked)return false;if(inFlight)return false;const serialized=JSON.stringify(payload());if(serialized===lastSaved)return true;
  const epoch=sessionEpoch;inFlight=true;cache(JSON.parse(serialized));status('Zapisywanie…','saving');
  try{const {data,error}=await client.rpc('bbf_save_workspace',{payload:JSON.parse(serialized),expected_revision:revision});if(epoch!==sessionEpoch)return false;if(error)throw error;
   revision=Number(data);lastSaved=serialized;if(JSON.stringify(payload())===serialized){localStorage.removeItem(pendingKey());status('Zapisano w chmurze');document.querySelector('#syncBanner').hidden=true}else{cache(payload());clearTimeout(timer);timer=setTimeout(flush,100)}return true;
  }catch(e){if(epoch!==sessionEpoch)return false;status('Niezapisane zmiany','error');if(String(e.message).includes('VERSION_CONFLICT')){blocked=true;document.querySelector('#app').inert=true;banner('Projekt zmieniono na innym urządzeniu. Twoje zmiany są zachowane lokalnie.',[['Pobierz moje zmiany',backup],['Wczytaj chmurę',async()=>{backup();localStorage.removeItem(pendingKey());document.querySelector('#syncBanner').hidden=true;await hydrate(user)}]])}else banner('Nie udało się zapisać danych. Zmiany pozostają na tym urządzeniu.',[['Ponów zapis',flush],['Pobierz kopię',backup]]);return false;
  }finally{inFlight=false}
 }
 async function logout(){if(JSON.stringify(payload())!==lastSaved&&!(await flush())){banner('Najpierw zapisz zmiany lub pobierz kopię.',[['Ponów zapis',flush],['Pobierz kopię',backup]]);return}const {error}=await client.auth.signOut();if(error){banner('Wylogowanie nie powiodło się. Spróbuj ponownie.');return}clearSession()}
 function clearSession(){sessionEpoch++;clearTimeout(timer);user=null;revision=0;lastSaved='';blocked=false;state=clone(defaults);state.projectTypes=clone(initialProjectTypes);state.targets={margin:null,retention:null};resetHistory();document.querySelector('#view').replaceChildren();document.querySelector('#projectGroups').replaceChildren();document.querySelector('#syncBanner').hidden=true;lock();document.querySelector('#authPassword').value=''}
 const previousSettings=renderSettings;renderSettings=function(){previousSettings();const section=document.createElement('section');section.className='card cloud-settings';section.innerHTML='<h3>Konto i dane</h3><p id="accountEmail"></p><div class="cloud-actions"><button class="ghost" id="cloudBackup">Pobierz kopię danych</button><button class="ghost" id="cloudImport">Przenieś dane z prototypu</button><button class="ghost" id="cloudLogout">Wyloguj</button></div><input hidden type="file" id="cloudImportFile" accept=".json,application/json">';document.querySelector('.page').prepend(section);section.querySelector('#accountEmail').textContent=user?.email||'';section.querySelector('#cloudBackup').onclick=backup;section.querySelector('#cloudLogout').onclick=logout;section.querySelector('#cloudImport').onclick=()=>{if(state.projects.length){showModal('<h3>Import do pustego konta</h3><p>To konto ma już projekty. Import nie zastąpi istniejących danych.</p><button class="ghost" onclick="closeModal()">Zamknij</button>');return}section.querySelector('#cloudImportFile').click()};section.querySelector('#cloudImportFile').onchange=async e=>{try{const file=e.target.files[0];if(!file)return;if(file.size>10*1024*1024)throw Error();const value=JSON.parse(await file.text());validateImport(value);showModal(`<h3>Przenieś dane do chmury</h3><p>${value.projects.length} projektów, ${value.clients.length} klientów, ${value.crew.length} osób, ${value.priceList.length} pozycji cennika.</p><div class="modal-actions"><button class="ghost" onclick="closeModal()">Anuluj</button><button class="primary" id="confirmCloudImport">Importuj na moje konto</button></div>`);document.querySelector('#confirmCloudImport').onclick=()=>{apply(value);closeModal();render();queueSave()}}catch(err){showModal('<h3>Nieprawidłowa kopia</h3><p>Wybierz plik JSON wyeksportowany z BBF Projects (do 10 MB).</p><button onclick="closeModal()">Zamknij</button>')}}};
 function validateImport(v){if(!v||!['projects','clients','crew','priceList'].every(k=>Array.isArray(v[k])))throw Error();for(const p of v.projects)if(typeof p.id!=='string'||typeof p.title!=='string'||!Array.isArray(p.rows)||!p.rows.every(r=>typeof r.id==='string'&&['item','category','subcategory'].includes(r.kind)))throw Error();if(!v.clients.every(c=>typeof c==='string'))throw Error();if(!v.crew.every(c=>c&&typeof c.id==='string'&&typeof c.name==='string'))throw Error();if(!v.priceList.every(c=>c&&typeof c.id==='string'&&typeof c.name==='string'))throw Error()}
 window.bbfCloud={queueSave,flush,validateImport};
 document.querySelector('#authForm').onsubmit=async e=>{e.preventDefault();message.textContent='Logowanie…';const submit=e.target.querySelector('[type=submit]');submit.disabled=true;const {error}=await client.auth.signInWithPassword({email:document.querySelector('#authEmail').value.trim(),password:document.querySelector('#authPassword').value});submit.disabled=false;if(error)message.textContent='Nie udało się zalogować. Sprawdź e-mail i hasło.'};
 document.querySelector('#magicLogin').onclick=async()=>{const email=document.querySelector('#authEmail').value.trim();if(!email){message.textContent='Wpisz adres e-mail.';return}const {error}=await client.auth.signInWithOtp({email,options:{shouldCreateUser:false,emailRedirectTo:location.origin+location.pathname}});message.textContent=error?'Nie udało się wysłać linku. Sprawdź konto i spróbuj później.':'Sprawdź skrzynkę e-mail — jeśli konto ma dostęp, otrzymasz link logowania.'};
 document.querySelector('#cloudRetry').onclick=()=>user?hydrate(user):location.reload();
 window.addEventListener('online',()=>flush());window.addEventListener('beforeunload',e=>{if(ready&&JSON.stringify(payload())!==lastSaved){e.preventDefault();e.returnValue=''}});
 lock();if(!config.supabaseUrl||!config.supabaseKey){message.textContent='Trwa konfiguracja aplikacji online.';document.querySelectorAll('#authGate button').forEach(b=>b.disabled=true);return}
 client=window.supabase.createClient(config.supabaseUrl,config.supabaseKey,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});
 client.auth.onAuthStateChange((event,session)=>{if(event==='SIGNED_OUT'){clearSession();return}if(session?.user&&session.user.id!==user?.id)setTimeout(()=>{if(session.user.id!==user?.id)hydrate(session.user)},0)});
 client.auth.getSession().then(({data:{session},error})=>{if(error){message.textContent='Nie można odczytać sesji. Zaloguj się ponownie.';return}if(session?.user&&session.user.id!==user?.id)hydrate(session.user)});
})();
