/* Authenticated, member-scoped, field-level persistence. No whole-document writes. */
(()=>{
 const config=window.BBF_CONFIG||{},M=window.BBFSyncModel,gate=$('#authGate'),message=$('#authMessage');
 let client,user,space,role,base={},revision=0,ready=false,busy=false,blocked=false,timer,poll,epoch=0,subscription,spaces=[];
 const tabId=sessionStorage.bbfTabId||(sessionStorage.bbfTabId=crypto.randomUUID());
 const cacheKey=()=>user&&space?'bbf-record-pending:'+user.id+':'+space+':'+tabId:null;
 const local=()=>M.pack(dataSnapshot());
 function status(text,error=false){const el=$('#saveState');if(el){el.textContent=text;el.dataset.sync=error?'error':''}}
 function lock(text='Zaloguj się, aby otworzyć projekty.'){ready=false;gate.hidden=false;document.documentElement.classList.add('auth-locked');message.textContent=text}
 function banner(text,actions=[]){const el=$('#syncBanner');el.replaceChildren(document.createTextNode(text));for(const [label,fn]of actions){const b=document.createElement('button');b.textContent=label;b.onclick=fn;el.append(b)}el.hidden=false}
 function backup(){download(new Blob([JSON.stringify(dataSnapshot(),null,2)],{type:'application/json'}),'BBF-kopia-danych.json')}
 function cache(){if(!ready||!cacheKey())return;try{localStorage.setItem(cacheKey(),JSON.stringify({base,local:local()}))}catch{banner('Nie udało się zachować kopii lokalnej. Pozostaw kartę otwartą do zakończenia zapisu.')}}
 function resetHistory(){timeline={base:dataSnapshot(),entries:[],cursor:0};updateHistoryButtons()}
 let needsRender=false;
 function apply(records,reset=false){const ui=state.ui;state={...clone(defaults),...M.unpack(records),ui};state.projectTypes??=clone(initialProjectTypes);state.targets??={margin:null,retention:null};state.projects.forEach(ensureStructure);if(!state.projects.some(p=>p.id===ui.selectedProject)){ui.selectedProject=state.projects[0]?.id;ui.tab=state.projects.length?'info':'dashboard'}if(reset)resetHistory();
  if(($('#typeMenu')||document.activeElement?.matches('input,textarea'))&&!document.documentElement.classList.contains('auth-locked')){needsRender=true;return}
  renderView();
 }
 function renderView(){const pageXY=[scrollX,scrollY];const shell=$('.sheet-page .table-shell'),xy=[shell?.scrollLeft||0,shell?.scrollTop||0],focus=document.activeElement?.closest('td')?.querySelector('[data-cell]'),id=focus?.dataset.rowid,key=focus?.dataset.cell;render();$('.sheet-page .table-shell')?.scrollTo(...xy);needsRender=false;document.body.classList.toggle('viewer-mode',role==='viewer');if(id&&key)window.bbfSheet?.selectId(id,key);window.scrollTo(...pageXY)}
 async function rpc(name,args){const {data,error}=await client.rpc(name,args);if(error)throw error;return data}
 async function hydrate(nextUser,nextSpace){const token=++epoch;user=nextUser;ready=false;blocked=false;clearInterval(poll);if(subscription)client.removeChannel(subscription);lock('Wczytywanie projektów…');
  try{spaces=await rpc('bbf_bootstrap',{});space=nextSpace||spaces[0]?.id;if(!space)throw Error('NO_SPACE');const snapshot=await rpc('bbf_snapshot',{s:space});if(token!==epoch)return;base=M.fromSnapshot(snapshot.entities);revision=snapshot.revision;role=snapshot.role;apply(base,true);ready=true;gate.hidden=true;document.documentElement.classList.remove('auth-locked');status(role==='viewer'?'Tylko odczyt':'Zapisano w chmurze');$('#cloudRetry').hidden=true;
   const pending=localStorage.getItem(cacheKey());if(pending){try{const saved=JSON.parse(pending),rebased=M.rebase(saved.base,saved.local,base);if(M.diff(saved.base,saved.local).length){apply(rebased.conflicts.length?saved.local:rebased.result);if(rebased.conflicts.length)conflict('Odnaleziono zmiany lokalne kolidujące z danymi w chmurze.');else queueSave()}}catch{banner('Nie można odczytać lokalnej kopii. Dane w chmurze są dostępne.')}}
   poll=setInterval(pull,3500);subscription=client.channel('bbf-space-'+space).on('postgres_changes',{event:'UPDATE',schema:'public',table:'bbf_spaces',filter:'id=eq.'+space},()=>pull()).subscribe();
  }catch(e){if(token!==epoch)return;lock('Nie udało się wczytać danych. Sprawdź połączenie i spróbuj ponownie.');$('#cloudRetry').hidden=false}
 }
 function conflict(text){blocked=true;status('Konflikt zmian',true);banner(text+' Twoje zmiany pozostają na tym urządzeniu.',[['Pobierz moją kopię',backup],['Wczytaj aktualne dane',async()=>{backup();localStorage.removeItem(cacheKey());await hydrate(user,space);$('#syncBanner').hidden=true}]])}
 function queueSave(){if(!ready||role==='viewer'||blocked)return;cache();clearTimeout(timer);timer=setTimeout(flush,600);if(M.diff(base,local()).length)status('Zapisywanie…')}
 async function flush(){if(!ready||blocked||role==='viewer')return false;if(busy)return false;const sent=local(),changes=M.diff(base,sent);if(!changes.length)return true;busy=true;const token=epoch;cache();
  try{const result=await rpc('bbf_apply_changes',{s:space,changes});if(token!==epoch)return false;const remote=M.fromSnapshot(result.entities),rebased=M.rebase(sent,local(),remote);base=remote;revision=result.revision;role=result.role;if(rebased.conflicts.length){conflict('Ta sama komórka została zmieniona równocześnie.');return false}apply(rebased.result,M.diff(sent,remote).length>0);if(M.diff(base,local()).length){cache();timer=setTimeout(flush,200)}else{localStorage.removeItem(cacheKey());status('Zapisano w chmurze');$('#syncBanner').hidden=true}return true;
  }catch(e){if(token!==epoch)return false;if(String(e.message).includes('CELL_CONFLICT'))conflict('Ta sama komórka została zmieniona przez inną osobę.');else{status('Niezapisane zmiany',true);banner('Zapis nie powiódł się. Zachowano zmiany lokalnie.',[['Ponów zapis',flush],['Pobierz kopię',backup]])}return false}finally{busy=false}
 }
 async function pull(){if(!ready||busy||blocked||document.visibilityState==='hidden')return;busy=true;const token=epoch;
  try{const snapshot=await rpc('bbf_snapshot',{s:space});if(token!==epoch||snapshot.revision===revision)return;const remote=M.fromSnapshot(snapshot.entities),rebased=M.rebase(base,local(),remote);if(rebased.conflicts.length){conflict('Inna osoba zmieniła tę samą komórkę.');return}base=remote;revision=snapshot.revision;role=snapshot.role;apply(rebased.result,true);if(M.diff(base,local()).length){cache();timer=setTimeout(flush,50)}else status('Zaktualizowano z chmury');
  }catch{status('Oczekiwanie na połączenie',true)}finally{busy=false}
 }
 function clear(){epoch++;clearTimeout(timer);clearInterval(poll);if(subscription)client.removeChannel(subscription);user=null;space=null;base={};ready=false;blocked=false;state=clone(defaults);state.projectTypes=clone(initialProjectTypes);state.targets={margin:null,retention:null};$('#view').replaceChildren();$('#projectGroups').replaceChildren();$('#syncBanner').hidden=true;resetHistory();lock();$('#authPassword').value=''}
 async function logout(){if(M.diff(base,local()).length&&!(await flush())){banner('Najpierw zapisz zmiany lub pobierz kopię.',[['Ponów zapis',flush],['Pobierz kopię',backup]]);return}const {error}=await client.auth.signOut();if(error){banner('Wylogowanie nie powiodło się.');return}clear()}
 const settings=renderSettings;renderSettings=function(){settings();const panel=document.createElement('section');panel.className='card cloud-settings';panel.innerHTML='<h3>Konto i współpraca</h3><p>'+esc(user?.email||'')+' · '+esc(({owner:'Właściciel',editor:'Edycja',viewer:'Tylko odczyt'})[role]||'')+'</p><select id="cloudSpace" aria-label="Zespół">'+spaces.map(s=>'<option value="'+s.id+'" '+(s.id===space?'selected':'')+'>'+esc(s.name)+'</option>').join('')+'</select><div class="cloud-actions"><button id="cloudBackup">Pobierz kopię danych</button><button id="cloudLogout">Wyloguj</button><button id="cloudMembers">Członkowie zespołu</button></div><div id="memberList"></div>';$('.page').prepend(panel);$('#cloudBackup').onclick=backup;$('#cloudLogout').onclick=logout;$('#cloudSpace').onchange=async e=>{if(M.diff(base,local()).length&&!(await flush()))return;await hydrate(user,e.target.value)};$('#cloudMembers').onclick=async()=>{try{const members=await rpc('bbf_members_list',{s:space});$('#memberList').innerHTML=members.map(m=>'<p>'+esc(m.email)+' · '+esc(({owner:'Właściciel',editor:'Edycja',viewer:'Tylko odczyt'})[m.role]||m.role)+'</p>').join('')+(role==='owner'?'<div class="field"><label>E-mail istniejącego konta aplikacji</label><input id="memberEmail" type="email"></div><select id="memberRole"><option value="editor">Edycja</option><option value="viewer">Odczyt</option></select><button id="memberAdd">Nadaj dostęp</button><p id="memberMessage"></p>':'');if($('#memberAdd'))$('#memberAdd').onclick=async()=>{try{await rpc('bbf_set_member',{s:space,email_address:$('#memberEmail').value,member_role:$('#memberRole').value});$('#cloudMembers').click()}catch{$('#memberMessage').textContent='Nie udało się nadać dostępu. Konto musi już istnieć w aplikacji.'}}}catch{banner('Nie udało się odczytać członków zespołu.')}}};
 function validateImport(v){if(!v||!['projects','clients','crew','priceList'].every(k=>Array.isArray(v[k])))throw Error();for(const p of v.projects)if(typeof p.id!=='string'||typeof p.title!=='string'||!Array.isArray(p.rows)||!p.rows.every(r=>typeof r.id==='string'&&['item','category','subcategory'].includes(r.kind)))throw Error();if(!v.clients.every(c=>typeof c==='string'))throw Error();if(!v.crew.every(c=>c&&typeof c.id==='string'&&typeof c.name==='string'))throw Error();if(!v.priceList.every(c=>c&&typeof c.id==='string'&&typeof c.name==='string'))throw Error()}
 const accountSettings=renderSettings;renderSettings=function(){accountSettings();if(role==='viewer')return;const actions=$('.cloud-actions');actions.insertAdjacentHTML('beforeend','<button id="cloudImport">Import kopii do pustego zespołu</button><input type="file" id="cloudImportFile" accept=".json,application/json" hidden>');$('#cloudImport').onclick=()=>{if(state.projects.length){banner('Import jest dostępny dla pustego zespołu. Obecne projekty pozostają bez zmian.');return}$('#cloudImportFile').click()};$('#cloudImportFile').onchange=async e=>{try{const file=e.target.files[0];if(!file)return;if(file.size>10*1024*1024)throw Error();const value=JSON.parse(await file.text());validateImport(value);showModal('<h3>Import kopii danych</h3><p>'+value.projects.length+' projektów. Dane zostaną zapisane w bieżącym pustym zespole.</p><button onclick="closeModal()">Anuluj</button><button id="confirmCloudImport">Importuj</button>');$('#confirmCloudImport').onclick=()=>{if(state.projects.length)return;apply(M.pack(value),true);closeModal();render();queueSave()}}catch{banner('Nieprawidłowa kopia. Wybierz plik JSON wyeksportowany z BBF Projects, do 10 MB.')}}};
 const oldDirty=dirty;dirty=function(label){if(role==='viewer'){apply(base,true);banner('Ten zespół jest dostępny tylko do odczytu.');return}oldDirty(label)};
 window.bbfCloud={queueSave,flush,pull,getRole:()=>role};
 $('#authForm').onsubmit=async e=>{e.preventDefault();message.textContent='Logowanie…';const b=e.target.querySelector('button');b.disabled=true;try{const {error}=await client.auth.signInWithPassword({email:$('#authEmail').value.trim(),password:$('#authPassword').value});if(error)message.textContent='Nie udało się zalogować. Sprawdź e-mail i hasło.'}catch{message.textContent='Brak połączenia. Spróbuj ponownie.'}finally{b.disabled=false}};
 $('#magicLogin').onclick=async()=>{const email=$('#authEmail').value.trim();if(!email){message.textContent='Wpisz adres e-mail.';return}try{const {error}=await client.auth.signInWithOtp({email,options:{shouldCreateUser:false,emailRedirectTo:location.origin+location.pathname}});message.textContent=error?'Nie udało się wysłać linku. Spróbuj później.':'Sprawdź skrzynkę e-mail — jeśli konto ma dostęp, otrzymasz link.'}catch{message.textContent='Brak połączenia.'}};
 $('#cloudRetry').onclick=()=>user?hydrate(user,space):location.reload();
 window.addEventListener('online',()=>flush());window.addEventListener('beforeunload',e=>{if(ready&&M.diff(base,local()).length){e.preventDefault();e.returnValue=''}});
 document.addEventListener('focusout',()=>{if(needsRender)setTimeout(()=>{if(!$('#typeMenu')&&!document.activeElement?.matches('input,textarea'))renderView()},0)});
 lock();if(!config.supabaseUrl||!config.supabaseKey){message.textContent='Brak konfiguracji połączenia.';return}
 client=window.supabase.createClient(config.supabaseUrl,config.supabaseKey,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});
 client.auth.onAuthStateChange((event,session)=>{if(event==='SIGNED_OUT'){clear();return}if(session?.user&&session.user.id!==user?.id)setTimeout(()=>{if(session.user.id!==user?.id)hydrate(session.user)},0)});
 client.auth.getSession().then(({data:{session}})=>{if(session?.user&&session.user.id!==user?.id)hydrate(session.user)});
})();
