/* Cashflow contract browser. No write operation is exposed. */
(()=>{
 const endpoint='https://ltyafffwvirfvmjrkzwj.supabase.co/functions/v1/projects-contracts';
 const button=document.createElement('button');button.className='nav-row';button.id='contractsBtn';button.innerHTML='<span class="nav-icon">▤</span><span>Pokaż umowy</span>';document.querySelector('.sidebar-bottom').prepend(button);
 let dialog,controller,blobUrl,all=[],selected,request=0;
 const date=v=>{if(!v)return '—';const d=new Date(v.length>10&&!/[Zz]|[+-]\d\d:\d\d$/.test(v)?v+'Z':v);return isNaN(d)?'—':d.toLocaleDateString('pl-PL',{timeZone:'Europe/Warsaw'})};
 const month=c=>{const parts=date(c.date).split('.');return parts.length===3?parts[2]+'-'+parts[1].padStart(2,'0'):''};
 const normalize=s=>String(s||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLocaleLowerCase('pl');
 const revoke=()=>{if(blobUrl){URL.revokeObjectURL(blobUrl);blobUrl=null}};
 const close=()=>{controller?.abort();request++;revoke();dialog?.remove();dialog=null;all=[];button.focus()};
 async function api(query='',pdf=false){const token=await window.bbfCloud.getAccessToken();const res=await fetch(endpoint+query,{headers:{Authorization:'Bearer '+token},signal:controller.signal,cache:'no-store'});if(!res.ok){const e=await res.json().catch(()=>({}));throw Error(e.error||'Nie udało się odczytać umów')}return pdf?res.blob():res.json()}
 function filters(){for(const [id,key] of [['contractType','type'],['contractProject','project']]){const select=dialog.querySelector('#'+id);for(const v of [...new Set(all.map(c=>c[key]).filter(Boolean))].sort((a,b)=>a.localeCompare(b,'pl'))){const o=document.createElement('option');o.value=v;o.textContent=v;select.append(o)}}}
 function draw(){const q=normalize(dialog.querySelector('#contractSearch').value),type=dialog.querySelector('#contractType').value,projectName=dialog.querySelector('#contractProject').value;const list=all.filter(c=>(!type||c.type===type)&&(!projectName||c.project===projectName)&&normalize([c.title,c.number,c.person,c.project,c.type,date(c.date)].join(' ')).includes(q));dialog.querySelector('#contractCount').textContent=list.length+' z '+all.length+' umów';
  list.sort((a,b)=>month(b).localeCompare(month(a))||String(a.number||'').localeCompare(String(b.number||''),'pl',{numeric:true})||String(a.title).localeCompare(String(b.title),'pl'));let previous=null;const tbody=dialog.querySelector('tbody');tbody.innerHTML=list.map(c=>{const key=month(c),heading=key!==previous?'<tr class="contract-month"><th colspan="8" scope="rowgroup">'+(key?new Date(key+'-15T12:00:00Z').toLocaleDateString('pl-PL',{month:'long',year:'numeric'}):'Bez daty')+'</th></tr>':'';previous=key;return heading+'<tr><td><button class="contract-open" data-contract="'+esc(c.id)+'">'+esc(c.title)+'</button><small>'+esc(c.number)+'</small></td><td>'+esc(c.person||'—')+'</td><td>'+esc(c.type)+'</td><td>'+esc(c.project||'—')+'</td><td>'+date(c.date)+'</td><td>'+date(c.paymentDate)+'</td><td class="contract-money">'+(c.net===null?'—':cur(c.net))+'</td><td>'+esc(c.status||'—')+'</td></tr>'}).join('');dialog.querySelector('#contractEmpty').hidden=!!list.length;tbody.querySelectorAll('[data-contract]').forEach(b=>b.onclick=()=>detail(b.dataset.contract));
 }
 async function detail(id){selected=id;const seq=++request;revoke();const c=all.find(c=>c.id===id),pane=dialog.querySelector('#contractDetail');pane.hidden=false;pane.innerHTML='<div class="contract-detail-head"><h3>'+esc(c.title)+'</h3><button id="contractBack">Zamknij podgląd</button></div><p>'+esc(c.person)+' · '+esc(c.project||'Bez projektu')+'</p><dl><div><dt>Typ</dt><dd>'+esc(c.type)+'</dd></div><div><dt>Netto</dt><dd>'+(c.net===null?'—':cur(c.net))+'</dd></div><div><dt>Data zawarcia</dt><dd>'+date(c.date)+'</dd></div><div><dt>Termin płatności</dt><dd>'+date(c.paymentDate)+'</dd></div><div><dt>Okres</dt><dd>'+date(c.start)+' – '+date(c.end)+'</dd></div></dl>'+(c.pdf?'<button id="contractPdf" class="primary">Pokaż PDF</button>':'<p class="contract-note">Brak pliku PDF w chmurze.</p>')+'<div id="contractContent" aria-live="polite">Wczytywanie treści…</div>';
  pane.querySelector('#contractBack').onclick=()=>{request++;revoke();pane.hidden=true;pane.replaceChildren()};if(c.pdf)pane.querySelector('#contractPdf').onclick=async e=>{const b=e.currentTarget;b.disabled=true;try{const blob=await api('?id='+encodeURIComponent(id)+'&pdf=1',true);if(seq!==request||!dialog)return;revoke();blobUrl=URL.createObjectURL(blob);const frame=document.createElement('iframe');frame.title='Podgląd umowy PDF';frame.src=blobUrl;const link=document.createElement('a');link.href=blobUrl;link.target='_blank';link.rel='noopener';link.textContent='Otwórz PDF w osobnej karcie';const content=pane.querySelector('#contractContent');content.replaceChildren(link,frame)}catch(err){if(seq===request&&dialog)pane.querySelector('#contractContent').textContent=err.message}finally{b.disabled=false}};
  try{const data=await api('?id='+encodeURIComponent(id));if(seq!==request||!dialog)return;const content=pane.querySelector('#contractContent'),pre=document.createElement('pre');pre.textContent=data.text||'Brak zapisanej treści umowy.';content.replaceChildren(pre);if(data.notes){const note=document.createElement('p');note.textContent='Notatki: '+data.notes;content.append(note)}}catch(e){if(seq===request&&dialog)pane.querySelector('#contractContent').textContent=e.message}pane.scrollIntoView({block:'nearest'});
 }
 async function load(){controller?.abort();controller=new AbortController();request++;const status=dialog.querySelector('#contractStatus');status.textContent='Wczytywanie umów z Cashflow…';try{const data=await api();if(!dialog)return;all=data.contracts.sort((a,b)=>String(b.date).localeCompare(String(a.date)));for(const id of ['contractType','contractProject']){const s=dialog.querySelector('#'+id);while(s.options.length>1)s.remove(1)}filters();draw();status.textContent='Big Bear Cashflow · stan danych: '+date(data.updatedAt)}catch(e){if(dialog&&e.name!=='AbortError')status.textContent=e.message}}
 button.onclick=()=>{if(dialog)return;dialog=document.createElement('dialog');dialog.className='contracts-dialog';dialog.innerHTML='<header><div><h2>Umowy</h2><span>Tylko do odczytu · Big Bear Cashflow</span></div><button id="contractsClose" aria-label="Zamknij przeglądarkę umów">×</button></header><div class="contract-filters"><input id="contractSearch" type="search" aria-label="Szukaj umowy" placeholder="Szukaj osoby, numeru lub projektu…"><select id="contractType" aria-label="Typ umowy"><option value="">Wszystkie typy</option></select><select id="contractProject" aria-label="Projekt umowy"><option value="">Wszystkie projekty</option></select><button id="contractsRefresh">Odśwież</button></div><div class="contract-status"><span id="contractStatus" role="status"></span><span id="contractCount"></span></div><div class="contract-table"><table><thead><tr><th>Umowa</th><th>Osoba / firma</th><th>Typ</th><th>Projekt</th><th>Data</th><th>Termin płatności</th><th>Kwota netto</th><th>Status</th></tr></thead><tbody></tbody></table><p id="contractEmpty" hidden>Brak umów pasujących do wyszukiwania.</p></div><section id="contractDetail" hidden></section>';document.body.append(dialog);dialog.showModal();dialog.addEventListener('cancel',e=>{e.preventDefault();close()});dialog.querySelector('#contractsClose').onclick=close;dialog.querySelector('#contractsRefresh').onclick=load;dialog.querySelector('#contractSearch').oninput=draw;dialog.querySelector('#contractType').onchange=draw;dialog.querySelector('#contractProject').onchange=draw;load()};
 new MutationObserver(()=>{if(document.documentElement.classList.contains('auth-locked')&&dialog)close()}).observe(document.documentElement,{attributes:true,attributeFilter:['class']});
})();
