/* Project details, compact reporting and consistent pickers. */
Object.assign(paths,{leaf:'M20 3C7 2 2 8 6 16s17 4 14-13Z M5 21 16 9',sprout:'M12 22V11 M12 15C3 15 2 10 3 5c7 0 10 3 9 10 M12 11c0-6 4-9 10-9 0 6-4 10-10 9',milk:'M8 2h8v5l3 4v11H5V11l3-4Z M8 7h8 M5 12h14 M3 3l18 18',checkcircle:'M21 11a9 9 0 1 1-6-8 M8 11l4 4L22 4'});
const statusIconNames=['receipt','calendar','video','checkcircle'];
const dietOptions=[['mięsny','food'],['wegan','leaf'],['wegetarianin','sprout'],['bez laktozy','milk'],['inne','food']];
const flatIcons=()=>Object.entries(Object.assign({},...Object.values(productionIcons),{leaf:'Rośliny',sprout:'Warzywa',milk:'Bez laktozy',checkcircle:'Zakończone'}));
function iconGrid(selected){return `<div class="flat-icon-grid">${flatIcons().map(([key,label])=>`<button type="button" data-flat-icon="${key}" title="${esc(label)}" aria-label="${esc(label)}" class="${key===selected?'selected':''}">${icon(key)}</button>`).join('')}</div>`}
function selectIcon(selected,apply,section){
 showModal(`<h3>Ikona${section?' i kolor':''}</h3>${iconGrid(selected)}${section?`<div class="color-chooser"><label for="sectionColor">Kolor podkategorii</label><input type="color" id="sectionColor" value="${section.color||'#4d87df'}"><button class="ghost" id="autoSectionColor">Automatyczny</button></div>`:''}<div class="modal-actions"><button class="ghost" onclick="closeModal()">Gotowe</button></div>`);
 $('#modal').querySelectorAll('[data-flat-icon]').forEach(b=>b.onclick=()=>{apply(b.dataset.flatIcon);closeModal()});
 if(section){$('#sectionColor').oninput=e=>{section.color=e.target.value;dirty('Zmieniono kolor podkategorii');document.querySelectorAll(`tr[data-row="${section.id}"]`).forEach(tr=>tr.style.setProperty('--section-accent',section.color))};$('#autoSectionColor').onclick=()=>{delete section.color;dirty('Automatyczny kolor podkategorii');const rows=project().rows.filter(r=>r.kind==='subcategory'),color=palette[rows.indexOf(section)%palette.length];document.querySelectorAll(`tr[data-row="${section.id}"]`).forEach(tr=>tr.style.setProperty('--section-accent',color));$('#sectionColor').value=color}};
}
iconModal=function(id){const row=project().rows.find(r=>r.id===id);$('#contextMenu').classList.remove('open');selectIcon(row.icon,key=>{row.icon=key;dirty('Zmieniono ikonę: '+row.name);document.querySelectorAll(`[data-icon="${id}"]`).forEach(b=>b.innerHTML=icon(key))},row.kind==='subcategory'?row:null)};
function closeDetailPopover(){$('#detailPopover')?.remove()}
function detailPopover(anchor,html){closeDetailPopover();const box=document.createElement('div');box.id='detailPopover';box.innerHTML=html;document.body.append(box);const r=anchor.getBoundingClientRect();box.style.left=Math.max(8,Math.min(r.left,innerWidth-box.offsetWidth-8))+'px';box.style.top=Math.max(8,Math.min(r.bottom+5,innerHeight-box.offsetHeight-8))+'px';box.onkeydown=e=>{const opts=[...box.querySelectorAll('button:not(:disabled)')],i=opts.indexOf(document.activeElement);if(['ArrowDown','ArrowUp'].includes(e.key)){e.preventDefault();opts[(i+(e.key==='ArrowDown'?1:-1)+opts.length)%opts.length]?.focus()}};return box}
function choicePicker(anchor,options,current,apply){const box=detailPopover(anchor,`<div class="detail-options" role="menu">${options.map(([value,key])=>`<button role="menuitemradio" aria-checked="${value===current}" data-detail-value="${esc(value)}">${icon(key)}<span>${esc(value)}</span>${value===current?icon('check'):''}</button>`).join('')}</div>`);box.querySelectorAll('[data-detail-value]').forEach(b=>b.onclick=()=>{apply(b.dataset.detailValue);closeDetailPopover()});box.querySelector('button')?.focus()}
const stableTypePicker=openTypePicker;
openTypePicker=function(button){stableTypePicker(button);const menu=$('#typeMenu'),branch=$('#bbfBranch');menu.classList.add('stable-type-menu');const r=button.getBoundingClientRect();menu.style.left=Math.max(8,Math.min(r.left,innerWidth-menu.offsetWidth-8))+'px';menu.style.top=Math.max(8,Math.min(r.bottom+4,innerHeight-menu.offsetHeight-8))+'px';const show=()=>{menu.querySelector('.price-options').hidden=false;branch.setAttribute('aria-expanded','true')};branch.onmouseenter=branch.onfocus=branch.onclick=show};
function infoField(label,content){return `<div class="field"><label>${label}</label>${content}</div>`}
renderInfo=function(){
 const p=project(),m=metrics(p),statusIcon=statusIconNames[statuses.indexOf(p.status)]||'folder',typeIcon=(state.projectTypes||initialProjectTypes).find(t=>t.name===p.type)?.icon||'folder';
 const dateLabels={contract:'Umowa',shoot:'Plan zdjęciowy',post:'Postprodukcja',crewPayment:'Płatność dla ekipy',clientPayment:'Płatność klienta'};
 const specs=[['Budżet',m.sales,'Przychód netto',''],['Przewidywany koszt',m.planned,'Koszty zewnętrzne',''],['Koszt zewnętrzny',m.actual,'Wykonanie',''],['Zasoby BBF',m.internal,'Według cennika',''],['Overhead',m.overhead,pct(p.overheadRate),''],['Retencja',m.retention,m.sales?pct(m.retention/m.sales):'—',m.retention<0?'negative':'positive'],['Marża',m.margin,m.sales?pct(m.margin/m.sales):'—',m.margin<0?'negative':'positive'],['Odchylenie',m.deviation,'Przewidywany − rzeczywisty',m.deviation<0?'negative':'positive']];
 $('#view').innerHTML=`<div class="page info-page"><div class="section-title"><h2>Informacje o projekcie</h2></div><div class="info-organization card"><div class="info-primary">${infoField('Ikona',`<button class="project-icon-editor" id="projectIconPicker" aria-label="Zmień ikonę projektu">${icon(p.icon||'file')}</button>`)}${infoField('Tytuł projektu',`<input data-pfield="title" value="${esc(p.title)}">`)}${infoField('Klient',`<input id="clientQuery" value="${esc(p.client)}" placeholder="Wyszukaj lub dodaj klienta…" role="combobox" aria-expanded="false" autocomplete="off">`)}</div><div class="info-secondary">${infoField('Status',`<button class="detail-select" data-project-choice="status">${icon(statusIcon)}<span>${esc(p.status)}</span>${icon('chevron')}</button>`)}${infoField('Typ projektu',`<button class="detail-select" data-project-choice="type">${icon(typeIcon)}<span>${esc(p.type)}</span>${icon('chevron')}</button>`)}${infoField('Overhead',`<div class="overhead-percent"><input data-overhead-percent inputmode="decimal" aria-label="Overhead w procentach" value="${+(num(p.overheadRate)*100).toFixed(4)}"><span>%</span></div>`)}</div><div class="info-dates">${Object.entries(dateLabels).map(([key,label])=>infoField(label,`<button class="detail-select date-button" data-date-picker="${key}">${icon('calendar')}<span>${p.dates?.[key]?new Date(p.dates[key]+'T12:00:00').toLocaleDateString('pl-PL'):'Wybierz datę'}</span></button>`)).join('')}</div></div><div class="kpis info-kpis">${specs.map(([label,val,sub,tone])=>kpi(label,cur(val),sub,tone)).join('')}</div>${financeCharts(p)}<div class="project-danger-zone"><button class="ghost danger-text" data-project-delete="${p.id}">${icon('trash')} Usuń projekt</button></div></div>`;
};
function clientPicker(input){const q=input.value.trim(),choices=state.clients.filter(c=>c.toLocaleLowerCase('pl').includes(q.toLocaleLowerCase('pl')));const box=detailPopover(input,`<div class="detail-options client-options" role="listbox">${choices.map(c=>`<button role="option" data-client-value="${esc(c)}">${icon('briefcase')}${esc(c)}</button>`).join('')}${q&&!state.clients.some(c=>c.toLocaleLowerCase('pl')===q.toLocaleLowerCase('pl'))?`<button role="option" data-client-value="${esc(q)}" class="add-client">${icon('plus')}Dodaj klienta: ${esc(q)}</button>`:''}${!q&&!choices.length?'<p>Wpisz nazwę nowego klienta.</p>':''}</div>`);input.setAttribute('aria-expanded','true');box.onpointerdown=e=>e.preventDefault();box.querySelectorAll('[data-client-value]').forEach(b=>b.onclick=()=>{const value=b.dataset.clientValue;if(!state.clients.includes(value))state.clients.push(value);project().client=value;dirty('Wybrano klienta: '+value);closeDetailPopover();render()})}
function calendarPicker(anchor,key,month){
 const p=project(),selected=p.dates?.[key]||'',date=month||new Date((selected||new Date().toISOString().slice(0,10))+'T12:00:00'),year=date.getFullYear(),mi=date.getMonth(),offset=(new Date(year,mi,1).getDay()+6)%7,count=new Date(year,mi+1,0).getDate();
 const box=detailPopover(anchor,`<div class="mini-calendar"><div class="calendar-heading"><button data-month-step="-1" aria-label="Poprzedni miesiąc">‹</button><strong>${date.toLocaleDateString('pl-PL',{month:'long',year:'numeric'})}</strong><button data-month-step="1" aria-label="Następny miesiąc">›</button></div><div class="calendar-grid">${['Pn','Wt','Śr','Cz','Pt','So','Nd'].map(x=>`<small>${x}</small>`).join('')}${'<span></span>'.repeat(offset)}${Array.from({length:count},(_,i)=>{const value=`${year}-${String(mi+1).padStart(2,'0')}-${String(i+1).padStart(2,'0')}`;return `<button data-calendar-date="${value}" class="${value===selected?'selected':''}" aria-label="${value}">${i+1}</button>`}).join('')}</div><div class="calendar-footer"><button data-calendar-date="${new Date().toLocaleDateString('sv-SE')}">Dzisiaj</button><button data-calendar-date="">Wyczyść</button></div></div>`);
 box.querySelectorAll('[data-month-step]').forEach(b=>b.onclick=()=>calendarPicker(anchor,key,new Date(year,mi+Number(b.dataset.monthStep),1)));
 box.querySelectorAll('[data-calendar-date]').forEach(b=>b.onclick=()=>{p.dates??={};p.dates[key]=b.dataset.calendarDate;dirty('Zmieniono termin projektu');closeDetailPopover();renderInfo()});
}
const detailedCrew=renderCrew;
renderCrew=function(){detailedCrew();const table=$('.crew-sheet');table.querySelector('thead th:last-child').innerHTML=icon('food')+' Wyżywienie';for(const tr of table.tBodies[0].rows){const id=tr.querySelector('[data-person-query]')?.dataset.personQuery,row=project().rows.find(r=>r.id===id),person=state.crew.find(p=>p.id===row?.personId);tr.lastElementChild.innerHTML=person?`<button class="diet-picker" data-crew-key="diet" data-diet-person="${person.id}">${icon(dietOptions.find(([v])=>v===person.diet)?.[1]||'food')} ${esc(person.diet||'Wybierz')}</button>`:'<span class="unassigned-cell">—</span>'}};
const detailedSettings=renderSettings;
renderSettings=function(){detailedSettings();$('.page').insertAdjacentHTML('beforeend',`<section class="card project-types-settings"><div class="section-title"><h3>Typy projektów</h3><button class="primary" id="addProjectType">${icon('plus')} Dodaj typ</button></div><div class="project-type-list">${(state.projectTypes||initialProjectTypes).map((t,i)=>`<button class="ghost" data-type-icon-index="${i}">${icon(t.icon)} ${esc(t.name)}</button>`).join('')}</div></section>`)};
function addProjectType(){let picked='folder';showModal(`<h3>Nowy typ projektu</h3><div class="field"><label>Nazwa</label><input id="newTypeName" placeholder="Nazwa typu"></div>${iconGrid(picked)}<div class="modal-actions"><button class="ghost" onclick="closeModal()">Anuluj</button><button class="primary" id="saveNewType">Dodaj typ</button></div>`);$('#modal').querySelectorAll('[data-flat-icon]').forEach(b=>b.onclick=()=>{picked=b.dataset.flatIcon;$('#modal').querySelectorAll('[data-flat-icon]').forEach(x=>x.classList.toggle('selected',x===b))});$('#saveNewType').onclick=()=>{const name=$('#newTypeName').value.trim();if(!name)return;state.projectTypes??=clone(initialProjectTypes);if(state.projectTypes.some(t=>t.name.toLowerCase()===name.toLowerCase())){$('#newTypeName').setCustomValidity('Ten typ już istnieje');$('#newTypeName').reportValidity();return}state.projectTypes.push({name,icon:picked});dirty('Dodano typ projektu');closeModal();renderSettings()}}
const detailDecorate=decorateSheet;
decorateSheet=function(){detailDecorate();const table=$('#settlementSheet');if(table){const first=table.querySelector('td[data-metric="actual"]');if(first){const index=first.cellIndex;[...table.tHead.rows[0].cells].forEach((cell,i)=>{if(i>=index)cell.classList.add('calculation-header');if(i===index)cell.classList.add('calculation-start')});table.querySelectorAll('td[data-metric="actual"]').forEach(cell=>cell.classList.add('calculation-start'))}}};
const detailRender=render;
render=function(){closeDetailPopover();detailRender();if(['info','estimate','settlement','crew'].includes(state.ui.tab)){state.ui.projectTab=state.ui.tab;save()}};
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!e.target.closest('#detailPopover')&&!e.target.closest('#clientQuery'))closeDetailPopover();if(!b)return;
 if(b.id==='projectIconPicker')selectIcon(project().icon,key=>{project().icon=key;dirty('Zmieniono ikonę projektu');render()});
 if(b.dataset.projectChoice){const key=b.dataset.projectChoice,options=key==='status'?statuses.map((s,i)=>[s,statusIconNames[i]]):(state.projectTypes||initialProjectTypes).map(t=>[t.name,t.icon]);choicePicker(b,options,project()[key],value=>{project()[key]=value;dirty('Zmieniono '+key);render()})}
 if(b.dataset.datePicker)calendarPicker(b,b.dataset.datePicker);
 if(b.dataset.dietPerson){const person=state.crew.find(p=>p.id===b.dataset.dietPerson);choicePicker(b,dietOptions,person.diet,value=>{person.diet=value;dirty('Zmieniono wyżywienie: '+person.name);renderCrew()})}
 if(b.id==='addProjectType')addProjectType();
 if(b.dataset.typeIconIndex!==undefined){const type=(state.projectTypes||initialProjectTypes)[Number(b.dataset.typeIconIndex)];selectIcon(type.icon,key=>{type.icon=key;dirty('Zmieniono ikonę typu');renderSettings()})}
});
document.addEventListener('input',e=>{if(e.target.id==='clientQuery')clientPicker(e.target)});
document.addEventListener('focusin',e=>{if(e.target.id==='clientQuery')clientPicker(e.target)});
document.addEventListener('focusout',e=>{if(e.target.id==='clientQuery'){if(e.relatedTarget?.closest('#detailPopover'))return;e.target.value=project().client||'';e.target.setAttribute('aria-expanded','false');closeDetailPopover()}});
document.addEventListener('keydown',e=>{if(e.key==='Escape')closeDetailPopover();if(e.target.id==='clientQuery'&&['Enter','ArrowDown'].includes(e.key)){e.preventDefault();const b=$('#detailPopover button');if(e.key==='Enter')b?.click();else {const box=$('#detailPopover');if(box)box.onpointerdown=null;b?.focus()}}});
render();
function reportDate(p){const raw=p.dates?.shoot||p.createdAt||new Date().toISOString();return new Date(raw.slice(0,10)+'T12:00:00')}
let reportingYear=new Date().getFullYear();
const annualSeries=[['sales','Przychód kosztorysowy','#4988ce'],['actual','Koszty zewnętrzne','#e0a45c'],['retention','Retencja','#4ba992'],['margin','Marża','#526477']];
function annualReports(){
 const years=[...new Set([new Date().getFullYear(),...state.projects.map(p=>reportDate(p).getFullYear()).filter(Number.isFinite)])].sort((a,b)=>b-a),projects=state.projects.filter(p=>reportDate(p).getFullYear()===reportingYear);
 const monthly=Array.from({length:12},()=>({sales:0,actual:0,retention:0,margin:0}));projects.forEach(p=>{const m=metrics(p),bucket=monthly[reportDate(p).getMonth()];for(const [key] of annualSeries)bucket[key]+=m[key]});
 const values=monthly.flatMap(m=>annualSeries.map(([k])=>m[k])),max=Math.max(1,...values),min=Math.min(0,...values),y=v=>220-(v-min)/(max-min)*190,zero=y(0),ticks=[min,(min+max)/2,max];
 const svg=`<svg class="annual-chart" viewBox="0 0 1000 275" role="img" aria-label="Miesięczny przychód, koszty zewnętrzne, retencja i marża w roku ${reportingYear}">${ticks.map(v=>`<line x1="78" x2="985" y1="${y(v)}" y2="${y(v)}" stroke="#e6edf5"/><text x="70" y="${y(v)+4}" text-anchor="end" font-size="10" fill="#8b9bb0">${Math.round(v).toLocaleString('pl-PL')}</text>`).join('')}${monthly.map((m,i)=>annualSeries.map(([k,label,color],j)=>`<rect x="${90+i*74+j*14}" y="${Math.min(y(m[k]),zero)}" width="11" height="${Math.abs(y(m[k])-zero)}" rx="2" fill="${color}"><title>${i+1}/${reportingYear} · ${label}: ${cur(m[k])}</title></rect>`).join('')+`<text x="${110+i*74}" y="247" text-anchor="middle" font-size="11" fill="#8095ae">${['sty','lut','mar','kwi','maj','cze','lip','sie','wrz','paź','lis','gru'][i]}</text>`).join('')}</svg>`;
 const grouped=key=>{const data=new Map();projects.forEach(p=>data.set(p[key]||'Nieprzypisany',(data.get(p[key]||'Nieprzypisany')||0)+metrics(p).sales));return [...data].sort((a,b)=>b[1]-a[1]).map(([label,value])=>({label,value}))},total=projects.reduce((n,p)=>n+metrics(p).sales,0);
 return `<section class="card annual-report"><div class="annual-heading"><div><h3>Wyniki w roku</h3><p>Według daty zdjęć; przy jej braku — daty utworzenia. Kwoty netto w zł.</p></div><select id="reportingYear" aria-label="Rok raportu">${years.map(y=>`<option ${y===reportingYear?'selected':''}>${y}</option>`).join('')}</select></div><div class="annual-stats">${annualSeries.map(([k,label])=>`<div><small>${label}</small><strong>${cur(monthly.reduce((n,m)=>n+m[k],0))}</strong></div>`).join('')}</div>${svg}<div class="annual-legend">${annualSeries.map(([,label,color])=>`<span><i style="background:${color}"></i>${label}</span>`).join('')}</div>${!projects.length?'<p>Brak projektów w wybranym roku.</p>':''}</section><div class="charts client-type-reports">${donut('Przychód według klientów',grouped('client'),String(reportingYear),cur(total))}${donut('Przychód według typów',grouped('type'),String(reportingYear),cur(total))}</div>`;
}
const detailedDashboard=renderDashboard;
renderDashboard=function(){detailedDashboard();$('.dashboard-intro').insertAdjacentHTML('afterend',`<div id="annualReports">${annualReports()}</div>`)};
document.addEventListener('change',e=>{if(e.target.id==='reportingYear'){reportingYear=Number(e.target.value);$('#annualReports').innerHTML=annualReports()}});
render();

document.addEventListener('input',e=>{if(e.target.hasAttribute('data-overhead-percent')){project().overheadRate=Math.max(0,num(e.target.value.replace('%','')))/100;dirty('Zmieniono overhead')}});
document.addEventListener('change',e=>{if(e.target.hasAttribute('data-overhead-percent'))renderInfo()});
